### ISSUE TITLE
Non-breakpoint media queries (eg "retina") are used to generate responsive widths

### ISSUE THREAD

**Issue by timswalling** [inuitcss/trumps.widths-responsive#12]
The 0.2.0 release (105b0b07844e656b9bf684db6f598b6fb48d6b6d) appears to have dropped the exclusion of `retina` breakpoints. This means that all media queries in the `$breakpoints` variable are converted into widths, whether they are wanted or not.

Although I've raised this as an issue with the responsive widths module, I think the best solution would actually be to leave this module intact, and to update the [responsive settings](https://github.com/inuitcss/settings.responsive) and [responsive tools](https://github.com/inuitcss/tools.responsive).

The responsive settings could be updated to include both a `$breakpoints` variable and a separate `$media-queries` variable (which is a superset of `$breakpoints`), while the responsive tools could be updated to use the `$media-queries` variable, with a fallback for anyone who is only using `$breakpoints`. [Here's what this might look like](http://sassmeister.com/gist/timswalling/d3ec7b86abc352ea3832).

If both files were also updated to use the map syntax proposed by @tymondesigns (see inuitcss/tools.responsive#7) it would make things easier to understand, as joining nested lists is a little messier than joining maps. [Here's what this might look like](http://sassmeister.com/gist/timswalling/1e21235ba6d4d4989827).

**Comment by timswalling** [comment]
Having played around with this a bit, I've realised it's possible to use maps for breakpoints and media queries but retain the existing logic for backwards compatibility: http://sassmeister.com/gist/timswalling/efc8fc7fa661999d6f3a

@csswizardry Would you accept a PR with these changes?

**Comment by aaronstezycki** [comment]
+1 this. :+1:

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
We are doing it all a bit different in the [new version](https://github.com/inuitcss/inuitcss) anyway.
If there are further issues with the new version, feel free to open a new issue in the [new repository](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md).

But thanks a lot for your time and your effort of pointing this out!
