### ISSUE TITLE
Wrong name in npm registry and a bunch of pull requests

### ISSUE THREAD

**Issue by Crawleyprint** [inuitcss/trumps.widths-responsive#8]
@csswizardry @nenadjelovac 

As title says it - name in npm registry is wrong and there are 3 pull requests already waiting. As #4 is the first one, I suggest you merge that one.

**Comment by yourownmood** [comment]
+1

**Comment by yourownmood** [comment]
+2 :)

**Comment by HammyNZ** [comment]
+3 :)

**Comment by jacquesletesson** [comment]
Same here.

**Comment by ryanturner10** [comment]
npm install --save inuit-responsive-widths

**Comment by uneart** [comment]
The typo still persists :)

**Comment by anandgraves** [comment]
+1
